export type RootStackParamList = {
  AuthLanding: undefined;
  SignIn: undefined;
  SignUp: { fromPhoneSignIn?: boolean; phone?: string } | undefined;
  ForgotPassword: undefined;
  Home: undefined;
  Orders: undefined;
  DrawOrders: undefined;
  ScratchOrders: undefined;
  Profile: undefined;
  AddFunds: undefined;
  PaymentMethod: undefined;
  ProcessingPayment: undefined;
  FundsAdded: undefined;
  AllScratchGames: undefined;
  AllDrawGames: undefined;
  GameHome: undefined;
  PickNumbers: undefined;
  YourPlays: undefined;
  ViewCart: undefined;
  OrderSummary: undefined;
  OrderProcessing: undefined;
  OrderSuccess: undefined;
  LuckyDream: undefined;
  LuckyDreamSummary: undefined;
  LuckyHoroscope: undefined;
  ScratchOrderCart: undefined;
  ScratchGameInfo: undefined;
  ScratchTicket: undefined;
  ScratchOrderDetails: undefined;
  DrawOrderDetails: undefined;
  PrizeNotifications: undefined;
  PrizeNotificationDetail: undefined;
  VerifyIdentity: undefined;
  SoftTierKyc: undefined;
  RegionBlocked: undefined;
};
