export type DrawGameNav = {
  id: string;
  slug?: string;
  name?: string;
  state?: string;
  draw_time?: string;
  cutoff_time?: string;
  jackpot?: number | string;
  bg_color?: string;
  draw_color?: string;
  price_per_play?: number | string;
  pricePerPlay?: number | string;
  pickableCount?: number;
  mainPickCount?: number;
};

export type ScratchGameNav = {
  id: string;
  name?: string;
  image_url?: string;
  top_prize?: number | string;
  price?: number | string;
  scratchable_areas?: unknown;
  available_tickets?: number;
};

export type RootStackParamList = {
  AuthLanding: undefined;
  SignIn: undefined;
  SignUp: { fromPhoneSignIn?: boolean; phone?: string } | undefined;
  ForgotPassword: undefined;
  Home: undefined;
  Orders: undefined;
  DrawOrders: undefined;
  ScratchOrders: undefined;
  Profile: undefined;
  AddFunds: undefined;
  PaymentMethod: undefined;
  ProcessingPayment: undefined;
  FundsAdded: undefined;
  AllScratchGames: undefined;
  AllDrawGames: undefined;
  GameHome: { game: DrawGameNav } | undefined;
  PickNumbers: undefined;
  YourPlays: undefined;
  ViewCart: undefined;
  OrderSummary: undefined;
  OrderProcessing: undefined;
  OrderSuccess: undefined;
  LuckyDream: undefined;
  LuckyDreamSummary: undefined;
  LuckyHoroscope: undefined;
  ScratchOrderCart: undefined;
  ScratchGameInfo: { gameId: string; game?: ScratchGameNav } | undefined;
  ScratchTicket: undefined;
  ScratchOrderDetails: undefined;
  DrawOrderDetails: undefined;
  PrizeNotifications: undefined;
  PrizeNotificationDetail: undefined;
  VerifyIdentity: undefined;
  SoftTierKyc: undefined;
  RegionBlocked: undefined;
};
